[package]
name = "backtest"
version = "0.1.0"
authors = ["Tianer Zhou <ezhoureal@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
chrono = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
ahash = { workspace = true }
rayon = { workspace = true }
polars = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }

[features]
live = []
