[package]
name = "ctp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
ctp2rs = { workspace = true }
backtest = { path = "../backtest", features = ["live"] }
polars = { workspace = true }
log = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
rand = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }

[features]
ctp_v6_7_11 = []
history_seed = []
